<?php return array (
  'DEFAULT_MODULE' => 'Wap',
  'DB_HOST' => '127.0.0.1',
  'DB_NAME' => 'sasa',
  'DB_USER' => 'root',
  'DB_PWD' => 'root',
  'DB_PORT' => '3306',
  'DB_PREFIX' => '77768688_',
  'URL_MODEL' => 0,
  'TMPL_FILE_DEPR' => '_',
  'WX_TOKEN' => 'haokuai',
  'DB_TYPE' => 'mysql',
  'TMPL_ACTION_SUCCESS' => './Application/Common/View/success.html',
  'TMPL_ACTION_ERROR' => './Application/Common/View/error.html',
);